### ISSUE TITLE
Add Remote API v1.15 support

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ahmetalpbalkan/Docker.DotNet#10]
Right now there's no Whatsnew section for 1.15: docker/docker/issues/8458

Once it is ready, update library with new features and changes.

**Comment by jgarverick** [comment]
Did you need anything else from me on this PR?  Just wondering as I can start to look at 1.16 if this one is all set.

**Comment by ahmetalpbalkan** [comment]
@jgarverick thank you so much! I guess we can just work on 1.16 (#12).
