### ISSUE TITLE
Add dependency to Microsoft.Bcl.Async

### ISSUE THREAD

**Issue by MaitreDede** [ahmetalpbalkan/Docker.DotNet#18]
Hi,

Can you add nuget dependency to Microsoft.Bcl.Async ?
Without it, I have exceptions about a missing assembly...

Thanks

**Comment by ahmetalpbalkan** [comment]
I wonder why we need that. We were able to use it without Microsoft.Bcl.Async. What is the full exception you get?

**Comment by MaitreDede** [comment]
FileNotFoundException for assembly : Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by ahmetalpbalkan** [comment]
@jgarverick any ideas? looks like a PCL issue.

**Comment by MaitreDede** [comment]
Why not making a plain 4.5 assembly ? You could add another project, but that does not rely on BCL assemblies/packages...

**Comment by jgarverick** [comment]
What target(s) are you trying to build for that it's giving you grief?
Just a plain ol' .NET 4.5 app?

We wanted to keep the code base in one compact library to make it easier to
maintain, hence the lack of pure 4.5 assembly.  I don't see any issue with
adding a dependency in the NuSpec file to make sure it pulls in BCL.Async,
though.  @ahmetalpbalkan, thoughts?

**Comment by MaitreDede** [comment]
I am just asking :)
I compile only 4.5 assemblies, (or 4.5.1). No BCL.
I don't know if having the BCL libs in pure 4.5 can have any impacts (that's why I am asking).

**Comment by ahmetalpbalkan** [comment]
@jgarverick I don't see any issues either. It's just I'm wondering why did this suddenly become a dependency.

**Comment by jgarverick** [comment]
It's always been a dependency, just not officially in the NuGet package
that's deployed AFAIK. When I started developing my app using the framework
I had to add it as well. I probably should have added it to the spec then
but I didn't think of it.

**Comment by ahmetalpbalkan** [comment]
Can you please send a PR? I wasnt aware of this :-) 




—Alp
http://alp.im

**Comment by ahmetalpbalkan** [comment]
Fixed now.
