### ISSUE TITLE
Add IDockerClient Interface

### ISSUE THREAD

**Issue by ryanwentzel** [ahmetalpbalkan/Docker.DotNet#21]
I'd like to begin using Docker.DotNet in a project. Adding an abstraction for `DockerClient` would help with unit testing code that uses this library. Something like:

```
public interface IDockerClient
{
    IImageOperations Images { get; }

    IContainerOperations Containers { get; }

    IMiscellaneousOperations Miscellaneous { get; }
}
```

Also, the return type for `DockerClientConfiguration.CreateClient()` could be changed to `IDockerClient`.

I'm open to submitting a PR, but wanted to check first whether you think this is valuable.

**Comment by ahmetalpbalkan** [comment]
Hi @ryanwentzel , yep that can help testing totally. Feel free to come up with some rough proposal or PR. I'd be happy to review.

However, isn't it fine if `CreateClient` returns a concrete type? It can be automatically downcasted to `IDockerClient`.

**Comment by jgarverick** [comment]
I get it...not only for stubbing unit tests but also DI if you decide to run with an IoC container. I don't see what it would hurt. Just my two cents. :)

**Comment by ahmetalpbalkan** [comment]
@jgarverick Actually, a few months ago, my plan was to test this client against an actual Docker daemon. Stubs and mocks are less effective in testing shims/client libraries than actually testing it. I'm OK with this change though. It doesn't hurt and makes use of existing interfaces.

**Comment by jgarverick** [comment]
No, it doesn't hurt at all.  Just to clarify, I was more referring to stubbing/mocking from a consumer perspective.  I agree that it doesn't make much sense to test this library with mocks since it's merely a wrapper for existing functionality that has already undergone unit testing.  Integration tests would be much more effective.  :+1:

**Comment by ppcherng** [comment]
Are there any plans to publish a new NuGet package that includes this change?

**Comment by ahmetalpbalkan** [comment]
@ppcherng I was being lazy creating a new NuGet package? Do you need this? If so I can publish a newer version for you.

**Comment by ppcherng** [comment]
Yes, it would be helpful for the project I'm working on, which uses DI and an IoC container. Thanks!

**Comment by rjperes** [comment]
This is already implemented and published in NuGet, so I think it can be closed.
