### ISSUE TITLE
System.IO.FileNotFoundExceptionCould not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0,

### ISSUE THREAD

**Issue by jchannon** [ahmetalpbalkan/Docker.DotNet#23]
Hi,

Just came across this project, looks great!

However I just ran the sample from README to list containers but when it calls this

```
 var containers = await client.Containers.ListContainersAsync(
                new ListContainersParameters()
                {
                    Limit = 10,
                });
```

I get an error like this:
```
System.IO.FileNotFoundExceptionCould not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Any ideas?

**Comment by jgarverick** [comment]
Hi Jonathan,
Do you have a reference added for Microsoft.Bcl.Async?  If not, you'll want
to do that as it handles the async/await goods.  If you do already have
that added to your project just let me know.

Josh

**Comment by jchannon** [comment]
Shouldnt that be a dependency in the nuspec then?

**Comment by jgarverick** [comment]
It will be for the next release, yes.

**Comment by jchannon** [comment]
:+1:
