### ISSUE TITLE
Integration Tests with Docker

### ISSUE THREAD

**Issue by jchannon** [ahmetalpbalkan/Docker.DotNet#25]
Hi,

Not sure this is really the place to comment but just thought I'd let you know that I'm looking at using this lib for integration tests for .net apps with xUnit.

Here's a link https://twitter.com/jchannon/status/601007895191408641

Having a few teething problems at the moment but I think its doable!

Keep up the good work!

**Comment by luisrudge** [comment]
Awesome work, @jchannon!

**Comment by ahmetalpbalkan** [comment]
This is a great use case, thanks for letting us know @jchannon.
