### ISSUE TITLE
Requests Are Ignored

### ISSUE THREAD

**Issue by rjperes** [ahmetalpbalkan/Docker.DotNet#26]
Hi,
Probably not the best place to ask this, but here it goes anyway...
I have a working installation of Docker, which I am trying to control with Docker.DotNet. The problem is, try as I might, I can't get any of the calls to return anything, but I also don't get any exceptions!
My basic code is:

var client = new DockerClientConfiguration(new Uri("tcp://192.168.99.100:2376")).CreateClient();
var containers = await client.Containers.ListContainersAsync(new ListContainersParameters());

I am monitoring the docker.log file, and I can see that no request gets there. Using the command line, everything works perfectly.
What can I be doing wrong?

Thanks!

RP

**Comment by rjperes** [comment]
Tried with and without X509 authentication, still nothing... The certificate is loaded, and the password is correct.

**Comment by ahmetalpbalkan** [comment]
Can you try using http instead of tcp?

**Comment by rjperes** [comment]
But for that I need to change the VM settings... Any other way I can debug Docker.DotNet? I try to pass even an invalid URL, but it always fails silently.

**Comment by ahmetalpbalkan** [comment]
Umm not really. tcp:// is what docker understands and it actually still uses http:// under the hoods. This library only uses http:// which should just work with your Docker engine configured to run on tcp://ip:port.

**Comment by rjperes** [comment]
It's the same thing, with HTTP, HTTPS or TCP. The docker.log file does not show any requests being received, whereas it does when I use the docker command line tool.

**Comment by rjperes** [comment]
I am using Visual Studio 2015, .NET 4.5.2, and I have the typical Docker environment variables set, which, for the command line, work perfectly.

**Comment by rjperes** [comment]
DOCKER_CERT_PATH=C:\Users\rperes\.docker\machine\machines\default
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1

**Comment by ahmetalpbalkan** [comment]
Well, your environment variables are not being used at all, in this case. This is the first time I'm hearing such a problem. I suggest checking out the source code and building symbols of this, this may give you a chance to debug by stepping into library code. 

Can you also paste the code that you used to initialize the client and made the API call?

**Comment by rjperes** [comment]
Sure:

var credentials = new CertificateCredentials(new X509Certificate2(Path.Combine(Environment.CurrentDirectory, "key.pfx"), "tcuser"));
var client = new DockerClientConfiguration(new Uri("tcp://192.168.99.100:2376"), credentials).CreateClient();

As you can see, I added the key.pfx file to the project, with "copy if newer" action, and used the same password as for the Docker VM. Password is ok, if I use an invalid one, I get an exception.
Then I'm doing something like:

var containers = await client.Containers.ListContainersAsync(new ListContainersParameters());

**Comment by rjperes** [comment]
BTW, I tried with both the DLL from NuGet and from a locally built one.

**Comment by rjperes** [comment]
Got it! :-D

**Comment by ahmetalpbalkan** [comment]
@rjperes ? Is it working now?

**Comment by rjperes** [comment]
It's the damn async stuff... :-)
Apparently, I was returning from the method without giving it time to actually perform the asynchronous operation! By using a ManualResetEvent I solved it, but I'm not sure it's the best way.
Do you understand my problem?

**Comment by ahmetalpbalkan** [comment]
Yeah I'm not really a System.Threading expert nowadays.. :) Glad it worked.

**Comment by rjperes** [comment]
Thanks, anyway!

**Comment by rjperes** [comment]
Sorry, just one more question: is there an API for the Docker run command?

**Comment by ahmetalpbalkan** [comment]
@rjperes `docker run` is not a single command. Please read this entire page if you're planning to use this library. http://docs.docker.com/reference/api/docker_remote_api_v1.20/#3-1-inside-docker-run
