### ISSUE TITLE
NuGet Package 1.1.2 Does Not Add Assembly

### ISSUE THREAD

**Issue by rjperes** [ahmetalpbalkan/Docker.DotNet#30]
The latest NuGet package, 1.1.2, does not include the Docker.DotNet assembly. Instead, it includes a single file named "_._" "inside the packages\Docker.DotNet.1.1.2\lib\portable-net45+sl5+wp8+win8" folder.

**Comment by ahmetalpbalkan** [comment]
@rjperes very interesting. I just pushed `1.1.2.1`, can you please give it a try? I saved it locally and inspected nupkg (below) before publishing.

> 
![image](https://cloud.githubusercontent.com/assets/159209/9411880/995c1d36-47dd-11e5-82ec-14e17bf9ee9d.png)

**Comment by ahmetalpbalkan** [comment]
@rjperes indeed there seems to be an issue with `1.1.2`, I just downloaded its nupkg from nuget and it doesn't match the one I have locally. I guess I clicked something wrong and removed dll just before publishing. :smile:

I'm using Nuget Package Explorer GUI to publish this every time, not sure if this stuff is possible to do with scripts. Apparently clicking things is error-prone. :smiley:

**Comment by ahmetalpbalkan** [comment]
should be fixed now.

**Comment by rjperes** [comment]
Yep, that did it! Thanks!

**Comment by rjperes** [comment]
BTW, what's the best place to discuss your library, ask questions, etc?

**Comment by ahmetalpbalkan** [comment]
Here.
