### ISSUE TITLE
Capture Output of Newly Created Container

### ISSUE THREAD

**Issue by rjperes** [ahmetalpbalkan/Docker.DotNet#32]
Hi,
For starting a new container and obtaining its output, I follow this workflow:

- CreateContainerAsync(id) (returns containerId)
- StartContainerAsync(id)
- GetContainerLogsAsync(containerId)

Am I doing it right or is there a better way? Specifically, how can I use the AttachStdout and AttachStderr parameters of the Config parameter of CreateContainerParameters?

Thanks!

**Comment by ahmetalpbalkan** [comment]
@rjperes Hi, your workflow seems correct. That's what the Docker client normally does.

Regarding your other question about Attach parameters, you should ask your question at Docker's dev channels/forums.
