### ISSUE TITLE
Docker Exec

### ISSUE THREAD

**Issue by rjperes** [ahmetalpbalkan/Docker.DotNet#34]
Hi,
Am I right to assume that right now it isn't possible to use the Docker EXEC command with Docker.DotNet?
Thanks!
RP

**Comment by ahmetalpbalkan** [comment]
Sounds about right. Implementation should be rather straightforward. Please consider contributing.

**Comment by rjperes** [comment]
I think I will!

**Comment by rjperes** [comment]
I just submitted a pull request: https://github.com/ahmetalpbalkan/Docker.DotNet/pull/35.
Waiting for your feedback!

**Comment by skarred14** [comment]
Hi, DockerDotNet API has really been useful to me for creating applications based on infrastructural changes and processes - thank you for such a string utility kit. Particularly, in reference to "ExecCreateContainerAsync", the method returns the ExecCreateContainerResponse object. However, I do not see the responsive action being executed. Here are the Config parameters that I entered: Config = new ExecCreateContainerConfig() {
                                                                                                    AttachStdin = true,
                                                                                                    AttachStdout = true,
                                                                                                    AttachStderr = true,
                                                                                                    Tty = true,
                                                                                                    Cmd = new List<string>() {
                                                                                                        "mkdir" , "abc"  }
                                                                                                }.
And here is the function call,
ExecCreateContainerResponse ex = await client.Containers.ExecCreateContainerAsync(cr.Id, new ExecCreateContainerParameters() { Config = ...<as given above>}
    );
where, cr.Id is the ID of the container that I have been able to create and run using CreateContainerAsync and StartContainerAsync. 
I expected that the outcome of the above instruction would result in the creation of a new directory "abc" within the container instance. Although the program executed successfully providing a valid ExecCreateContainerResponse (Id, Warnings), when I looked up, by attaching the container on console, I couldnt find the directory. Could you please suggest, as to how this can be achieved - I am trying to get to a result similar to "docker exec -d containerName mkdir abc" on console prompt.

**Comment by ahmetalpbalkan** [comment]
@skarred14 please open another separate issue about your problem. This originally reported ossue is apparently resolved with a submitted patch.
