### ISSUE TITLE
Using ExecCreateContainerResponse and ExecCreateContainerAsync

### ISSUE THREAD

**Issue by skarred14** [ahmetalpbalkan/Docker.DotNet#44]
Hi, DockerDotNet API has really been useful to me for creating applications based on infrastructural changes and processes - thank you for such a string utility kit. Particularly, in reference to `ExecCreateContainerAsync`, the method returns the `ExecCreateContainerResponse` object. However, I do not see the responsive action being executed. Here are the Config parameters that I entered: 

```cs
Config = new ExecCreateContainerConfig() {
AttachStdin = true,
AttachStdout = true,
AttachStderr = true,
Tty = true,
Cmd = new List<string>() {"mkdir" , "abc"  }
}
```

And here is the function call,

```
ExecCreateContainerResponse ex = await client.Containers.ExecCreateContainerAsync(cr.Id, new ExecCreateContainerParameters() { Config = ...<as given above>});
```

where, cr.Id is the ID of the container that I have been able to create and run using CreateContainerAsync and StartContainerAsync. 
I expected that the outcome of the above instruction would result in the creation of a new directory "abc" within the container instance. Although the program executed successfully providing a valid ExecCreateContainerResponse (Id, Warnings), when I looked up, by attaching the container on console, I couldnt find the directory. My questions:

1. How can this action be achieved  - I am trying to get to a result similar to "docker exec -d containerName mkdir abc" on console prompt?
2. In a general scenario, if the CMD were to be an instruction that produces a stream of output on screen, how can this execution be achieved and the result be viewed on Visual Studio console?

**Comment by ahmetalpbalkan** [comment]
I've never used this method personally, @rjperes any ideas?

@skarred14 I have no ideas about Visual Studio, however if you're referring to `exec -i -t`, please read Remote API docs on Docker documentation and look at docker engine logs to see what http calls are made to the engine to achieve that. They may be using a combination of exec+attach. Also for this request, do you see any http calls logged in the docker engine's logs?

**Comment by skarred14** [comment]
Thanks for the response - I was indeed looking for an equivalent of exec -i -t. I have gone through the docker remote api, and it looks like there needs to be another Task for ExecStartContainer - corresponding to Exec Start (/exec{0}/start}. The response for this is a stream resposne, {{ STREAM }}. In the near future would there be any updates to include ExecStartContainer API? Meanwhile, I have been trying to create a separate class file, similar to the structure of the library, specifically for this container operation. I am right now stumbling at the point where I am unable to use any of the functions in DockerClient owing to its protection level. Suggestions?

**Comment by ahmetalpbalkan** [comment]
@skarred14 download the entire repository source and add to your solution as project? So you can extend the code and debug.

**Comment by skarred14** [comment]
I have been able to extend the library to include a new call for ExecStartContainerAsync. Here is the sequence of operations: Create container (using CreateContainerAsync); Start container (using StartContainerAsync); Create an exec instance (using ExecCreateContainerAsync); Start the exec instance(new call, ExecStartContainerAsync), by leveraging the exec instance id created during the creation of the exec instance. The program runs successfully and by creating an instance with Cmd = {"mkdir" "abc"}, the folder did indeed get created within the container.  Here is the line in the main program:
Stream exs = await client.Containers.ExecStartContainerAsync(ex.Id,new ExecStartContainerParameters() {
                                                                                                StartConfig = new ExecStartContainerConfig(){ 
                                                                                                                Detach = false,
                                                                                                                Tty = false            
}
            },CancellationToken.None);

**Comment by ahmetalpbalkan** [comment]
Do you mind sending a pull request if you think other people might use it
too?
On Fri, Jan 15, 2016 at 9:39 PM skarred14 <notifications@github.com> wrote:

> I have been able to extend the library to include a new call for
> ExecStartContainerAsync. Here is the sequence of operations: Create
> container (using CreateContainerAsync); Start container (using
> StartContainerAsync); Create an exec instance (using
> ExecCreateContainerAsync); Start the exec instance(new call,
> ExecStartContainerAsync), by leveraging the exec instance id created during
> the creation of the exec instance. The program runs successfully and by
> creating an instance with Cmd = {"mkdir" "abc"}, the folder did indeed get
> created within the container. Here is the line in the main program:
> Stream exs = await client.Containers.ExecStartContainerAsync(ex.Id,new
> ExecStartContainerParameters() {
> StartConfig = new ExecStartContainerConfig(){
> Detach = false,
> Tty = false
>
> }
> },CancellationToken.None);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahmetalpbalkan/Docker.DotNet/issues/44#issuecomment-172160738>
> .
>
-- 
—Ahmet Alp Balkan

**Comment by dudes-come** [comment]
I have the same problem, ExecCreateContainerAsync execute nothing, my code is

``` csharp
var execResponse = await client.Containers.ExecCreateContainerAsync(
	containerId, new ContainerExecCreateParameters()
	{
		Detach = false,
		Tty = true,
		Cmd = new[]
		{
			"mkdir", "abc"
		}
	})
```

this command return success but no folder name "abc" created

**Comment by BritoMatheus** [comment]
@dudes-come  It will generate some ID, so you need to start this Exec with this ID

```
var execResponse = await client.Containers.ExecCreateContainerAsync(
	containerId, new ContainerExecCreateParameters()
	{
		Detach = false,
		Tty = true,
		Cmd = new[]
		{
			"mkdir", "abc"
		}
	});

await client.Containers.StartContainerExecAsync(execResponse.ID);

```
