### ISSUE TITLE
Support run with --rm option

### ISSUE THREAD

**Issue by rjperes** [ahmetalpbalkan/Docker.DotNet#45]
Docker allows starting new instances with the --rm option; what it does is, after the container execution ends, the container is removed.
If there is interest, I can submit a pull request.

**Comment by ahmetalpbalkan** [comment]
@rjperes I think this goes beyond this library's responsibility, it's a client-side operation that can be already done by using the methods from this client library.

Wouldn't it be simply 

    try { run() } finally { rm() }

?

**Comment by ahmetalpbalkan** [comment]
Also --rm can be used only when you're attaching to the container in interactive mode. I'm not sure if there's anybody using this library in interactive mode, .NET simply doesn't have an http hijacking implementation.

**Comment by rjperes** [comment]
You are right... it is a command line thing. Apparently, there was a discussion to move it to the daemon, but it has gone nowhere.
I'm gonna close this issue, as it doesn't make sense.
