### ISSUE TITLE
X509 NuGet Package Out of Date

### ISSUE THREAD

**Issue by kruzty** [ahmetalpbalkan/Docker.DotNet#46]
The latest Docker.DotNet.X509 NuGet package appears to be out of sync with the latest Docker.DotNet package. When I attempt to create a CertificateCredentials object, the following exception is thrown:
> Error starting session: Method 'get_Handler' in type 'Docker.DotNet.X509.CertificateCredentials' from assembly 'Docker.DotNet.X509, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by ahmetalpbalkan** [comment]
@kruzty you are right. Sorry I did not notice we changed that package during a recent pull request. I am hoping to push a fixed version for X509 package on NuGet today!

**Comment by ahmetalpbalkan** [comment]
@kruzty Sorry for the late response here. I just pushed v1.2.2 for:

https://www.nuget.org/packages/Docker.DotNet.X509/
https://www.nuget.org/packages/Docker.DotNet.BasicAuth/
