### ISSUE TITLE
X509 not suport DNXcore

### ISSUE THREAD

**Issue by mateusdemboski** [ahmetalpbalkan/Docker.DotNet#47]
I trying install the library Docker.DotNet.X509 on my ASP.NET Core project, but VS it's displaying the mensage 'NU1002 The dependency Docker.DotNet.X509 1.2.2 in project <ProjectName> does not support framework DNXCore,Version=v5.0.'

How i can fix this? or is a bug?

Regards

**Comment by ahmetalpbalkan** [comment]
The package probably doesn't support .net core.

**Comment by mateusdemboski** [comment]
Any chance to be ported ou compatible in the future?
My project depend of this library... =(

**Comment by ahmetalpbalkan** [comment]
@mateusdemboski well, you can try porting the .x509 package to .net core and send as a pull request, I'd happily package it for you.

**Comment by jstarks** [comment]
I believe we will have a solution for this soon.

**Comment by ahmetalpbalkan** [comment]
@swernli  so is this fixed with #50 merged?

**Comment by swernli** [comment]
Unfortunately, no.  X509 auth implementation still depends on types that aren't present in DNXCore.  This will need to be fixed in a later PR.

**Comment by jstarks** [comment]
Should be fixed now.
