### ISSUE TITLE
.NET 2.0 support?

### ISSUE THREAD

**Issue by predominant** [ahmetalpbalkan/Docker.DotNet#48]
I notice `TargetFrameworkVersion` is `v4.0`.

I'm wondering if this would work on .NET 2?

Cheers

**Comment by ahmetalpbalkan** [comment]
@predominant I'm not sure. Feel free to try it out.

**Comment by ahmetalpbalkan** [comment]
also, you should modernize your environment sometime. :wink:  .NET 2.0 came out 10 years ago.

**Comment by predominant** [comment]
@ahmetalpbalkan I'm modern ;) Its just that Unity3D still uses .NET 2.0 :(

**Comment by jterry75** [comment]
This will not work without some pretty significant changes and `#ifdef` work. We leverage quite a few functions that were not available from HTTP and Buffers in .NET 2.0

**Comment by predominant** [comment]
Cheers, thanks 👍
