### ISSUE TITLE
Project should compile for netcore50 using latest dotnet CLI

### ISSUE THREAD

**Issue by swernli** [ahmetalpbalkan/Docker.DotNet#56]
The project.json file isn't in the right format to allow publishing for netcore50 on our desired runtimes with the latest dotnet CLI.  https://github.com/ahmetalpbalkan/Docker.DotNet/pull/55 temporarily removes support for netstandard1.3 as a work-around, but long term we'd like to have the correct project.json to support netcore properly.

**Comment by jterry75** [comment]
#57

**Comment by jterry75** [comment]
This wasnt fixed correctly after recent changes.

**Comment by jterry75** [comment]
New PR on its way.
