### ISSUE TITLE
How to call remote shell commands in container?

### ISSUE THREAD

**Issue by ChenZhaobin** [ahmetalpbalkan/Docker.DotNet#78]
I am so lucky to see Docker.DotNet.
Maybe this  question is just  about docker remote api.I want to know how can I remote post commands to shell in docker container.for example post "Python -V" to remote docker container?

**Comment by ahmetalpbalkan** [comment]
@ChenZhaobin I'm assuming you want to specify an entrypoint for a container image. For that, you should check out the `Entrypoint` and `Cmd` fields on the `Config` type. Your question seems like it's more about the Docker Remote API than the .NET library. I suggest reading the API docs first https://docs.docker.com/engine/reference/api/docker_remote_api/
