### ISSUE TITLE
LogConfig property not available?

### ISSUE THREAD

**Issue by robborden** [ahmetalpbalkan/Docker.DotNet#84]
First of all, thanks for this great library.   I'm trying to set some LogOptions within CreateContainerParameters.  However, the CreatContainerParameters.Config.HotConfig.LogConfig property does not appear to be exposed, even though I see it in the source code. 

I am using NuGet package version 1.2.2 according to NuGet package manager in VS.  When I right-click and go to properties on the Docker.DotNet reference, it says version 1.0.0.0.  I also don't see the "LogFile" property on the HostConfig class in the object browser.  Is it possible NuGet somehow installed the wrong version?  When I go into the package manager, it still says v1.2.2.

**Comment by robborden** [comment]
Hm... It seems the most recently updated NuGet package for this project only supports Docker Remote API 1.16.  Current version is v1.23, I'm attempting to build the lib myself, so far unsuccessfully.  Will update here if/when I get it working.

**Comment by jterry75** [comment]
@robborden - We are actively working out how best to move forward publishing this nuget package. For now the most recently published to nuget is v1.2.2 is not the most recent code. We actually support the docker v1.24 Remote API but you will need to build the Docker.Net locally and include the nupkg. You should be able to use the dotnet cli to `dotnet build` if you want the binaries and `dotnet pack` it you want them packaged into a *.nupkg. I hope this helps for now.

**Comment by robborden** [comment]
Thank you for your reply.  After i replaced an older DNX SDK with the new rc2 SDK, I was able to compile and use the library.  I have noticed a possible issue, but I will start a new thread.
